In [14]:
import numpy as np

In [16]:
a = [1,2,3,4,5,6,7,8,9,10]
print(a)
print(type(a))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


In [18]:
a = np.array([1,2,3,4,5,6,7,8,9,10]) #numpy array 
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


# ndim function

In [21]:
#ndim :- to check dimension
print(a.ndim)

1


In [31]:
#two dimension
b_2d = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(b_2d)
print("dimension of array is:",b_2d.ndim)

[[1 2 3 4 5]
 [2 3 4 5 6]]
dimension of array is: 2


In [43]:
#three dimension
c_3d = np.array([[[1,2,3],[4,5,6],[7,8,5]],[[1,1,1],[2,2,2],[3,3,3]]])
print(c_3d)
print(type(c_3d))
print("dimension of array is : ",c_3d.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 5]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]]
<class 'numpy.ndarray'>
dimension of array is :  3


In [39]:
#5X5 matrix
c_3d = np.array([[1,2,3,4,5],[4,5,6,8,9],[7,8,5,7,9],[1,1,1,5,6],[2,2,2,4,5]])
print(c_3d)
print(type(c_3d))
print("dimension of array is : ",c_3d.ndim)

[[1 2 3 4 5]
 [4 5 6 8 9]
 [7 8 5 7 9]
 [1 1 1 5 6]
 [2 2 2 4 5]]
<class 'numpy.ndarray'>
dimension of array is :  2


In [36]:
c_3d = np.array([[[1,2],[4,5]],[[1,1],[2,2]],[[1,1],[2,2]]])
print(c_3d)
print(type(c_3d))
print("dimension of array is : ",c_3d.ndim)

[[[1 2]
  [4 5]]

 [[1 1]
  [2 2]]

 [[1 1]
  [2 2]]]
<class 'numpy.ndarray'>
dimension of array is :  3


# size function

In [40]:
# size
b_2d = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(b_2d)
print(b_2d.size)

[[1 2 3 4 5]
 [2 3 4 5 6]]
10


In [44]:
c_3d = np.array([[[1,2,3],[4,5,6],[7,8,5]],[[1,1,1],[2,2,2],[3,3,3]]])
print(c_3d)
print(c_3d.size)

[[[1 2 3]
  [4 5 6]
  [7 8 5]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]]
18


# shape function

In [45]:
#shape function 
#shows no. of rows and column
b_2d = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(b_2d)
print(b_2d.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [46]:
c_3d = np.array([[1,2,3,4,5],[4,5,6,8,9],[7,8,5,7,9],[1,1,1,5,6],[2,2,2,4,5]])
print(c_3d)
print(c_3d.shape)

[[1 2 3 4 5]
 [4 5 6 8 9]
 [7 8 5 7 9]
 [1 1 1 5 6]
 [2 2 2 4 5]]
(5, 5)


In [47]:
#dtype
#gives the type of data which type of data it is storing whether int , float , etc
c_3d = np.array([[1,2,3,4,5],[4,5,6,8,9],[7,8,5,7,9],[1,1,1,5,6],[2,2,2,4,5]])
print(c_3d)
print(c_3d.dtype)

[[1 2 3 4 5]
 [4 5 6 8 9]
 [7 8 5 7 9]
 [1 1 1 5 6]
 [2 2 2 4 5]]
int32


In [50]:
c_array = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(c_array)
c_array_2 = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(c_array_2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


# ones and zeros

In [62]:
#creating  matrix by ones and zeros function
a= np.ones([4,4] , dtype = int)
print(a)
b = np.zeros([3,3],dtype = int)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [65]:
a= np.ones([4,4] , dtype = str)
print(a)
b = np.zeros([3,3],dtype = str) # blank matrix will occur
print(b)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
[['' '' '']
 ['' '' '']
 ['' '' '']]


In [67]:
a= np.ones([4,4] , dtype = bool)
print(a)
b = np.zeros([3,3],dtype = bool)
print(b)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False]
 [False False False]
 [False False False]]


# empty function

In [72]:
em_mx = np.empty((4,4)) # gives garbage value
print(em_mx)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# arrange function

In [75]:
#syntax :- np.arange(start_value , end_value , step)
ar_1d = np.arange(13)
print(ar_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [78]:
ar_1d = np.arange(1 , 100)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [85]:
ar_1d = np.arange(1 , 100 , 1)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


# linspace function

In [97]:
#syntax :- np.linspace(start_value , end_value , np of value b/w start and end)
np.linspace(1,2,50)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [100]:
np.linspace(1,100,10) #difference is same b/w values

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [102]:
s = np.linspace(1,10,25)
print(s)

[ 1.     1.375  1.75   2.125  2.5    2.875  3.25   3.625  4.     4.375
  4.75   5.125  5.5    5.875  6.25   6.625  7.     7.375  7.75   8.125
  8.5    8.875  9.25   9.625 10.   ]


# resahpe function

In [107]:
print("one dimension array by linspace")
s = np.linspace(1,10,25)
print(s)
d = s.reshape(5,5)
print(d)


one dimension array by linspace
[ 1.     1.375  1.75   2.125  2.5    2.875  3.25   3.625  4.     4.375
  4.75   5.125  5.5    5.875  6.25   6.625  7.     7.375  7.75   8.125
  8.5    8.875  9.25   9.625 10.   ]
[[ 1.     1.375  1.75   2.125  2.5  ]
 [ 2.875  3.25   3.625  4.     4.375]
 [ 4.75   5.125  5.5    5.875  6.25 ]
 [ 6.625  7.     7.375  7.75   8.125]
 [ 8.5    8.875  9.25   9.625 10.   ]]


In [119]:
print("by linspace function:")

arr = np.linspace(1,12,12 , dtype = int)
arr2 = arr.reshape(3,2,2)
print(arr2)
print(arr)
print("by arange function:")
array_1 = np.arange(1,13,1)
print(array_1)
array_2 = array_1.reshape(3,2,2)
print(array_2)

by linspace function: [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
by arange function:[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# ravel function

In [120]:
#convert multi dimensional to one dimensional
c_3d = np.array([[[1,2,3],[4,5,6],[7,8,5]],[[1,1,1],[2,2,2],[3,3,3]]])
c_3d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 1, 1, 1, 2, 2, 2, 3, 3, 3])

# transpose function

In [125]:
#transpose() or T() row to column or column to row
c_3d = np.array([[1,2,3,4,5],[4,5,6,8,9],[7,8,5,7,9],[1,1,1,5,6],[2,2,2,4,5]])
# c_3d.transpose()
c_3d.T

array([[1, 4, 7, 1, 2],
       [2, 5, 8, 1, 2],
       [3, 6, 5, 1, 2],
       [4, 8, 7, 5, 4],
       [5, 9, 9, 6, 5]])

In [133]:
array1 = np.arange(1,10).reshape(3,3)
array2 = np.arange(1,10).reshape(3,3)
print(array1)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# mathematical operation using Numpy

In [134]:
print(array1+array2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [135]:
print(array1-array2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [136]:
print(array1*array2) #this is not actual matrix multiplication(elemenmt to element)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [139]:
print(array1@array2)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [141]:
print(array1.dot(array2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [142]:
np.add(array1,array2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [145]:
np.divide(array1,array2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [147]:
np.subtract(array1,array2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])