# Numpy 

In [7]:
import numpy as np

In [1]:
a = [1,2,3,4,5,6,7,8,9,10]
print(a)
print(type(a))

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10]) #numpy array 
print(a)
print(type(a))

# ndim function

In [21]:
#ndim :- to check dimension
print(a.ndim)

1


In [31]:
#two dimension
b_2d = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(b_2d)
print("dimension of array is:",b_2d.ndim)

[[1 2 3 4 5]
 [2 3 4 5 6]]
dimension of array is: 2


In [43]:
#three dimension
c_3d = np.array([[[1,2,3],[4,5,6],[7,8,5]],[[1,1,1],[2,2,2],[3,3,3]]])
print(c_3d)
print(type(c_3d))
print("dimension of array is : ",c_3d.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 5]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]]
<class 'numpy.ndarray'>
dimension of array is :  3


In [39]:
#5X5 matrix
c_3d = np.array([[1,2,3,4,5],[4,5,6,8,9],[7,8,5,7,9],[1,1,1,5,6],[2,2,2,4,5]])
print(c_3d)
print(type(c_3d))
print("dimension of array is : ",c_3d.ndim)

[[1 2 3 4 5]
 [4 5 6 8 9]
 [7 8 5 7 9]
 [1 1 1 5 6]
 [2 2 2 4 5]]
<class 'numpy.ndarray'>
dimension of array is :  2


In [36]:
c_3d = np.array([[[1,2],[4,5]],[[1,1],[2,2]],[[1,1],[2,2]]])
print(c_3d)
print(type(c_3d))
print("dimension of array is : ",c_3d.ndim)

[[[1 2]
  [4 5]]

 [[1 1]
  [2 2]]

 [[1 1]
  [2 2]]]
<class 'numpy.ndarray'>
dimension of array is :  3


# size function

In [40]:
# size
b_2d = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(b_2d)
print(b_2d.size)

[[1 2 3 4 5]
 [2 3 4 5 6]]
10


In [44]:
c_3d = np.array([[[1,2,3],[4,5,6],[7,8,5]],[[1,1,1],[2,2,2],[3,3,3]]])
print(c_3d)
print(c_3d.size)

[[[1 2 3]
  [4 5 6]
  [7 8 5]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]]
18


# shape function

In [45]:
#shape function 
#shows no. of rows and column
b_2d = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(b_2d)
print(b_2d.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [46]:
c_3d = np.array([[1,2,3,4,5],[4,5,6,8,9],[7,8,5,7,9],[1,1,1,5,6],[2,2,2,4,5]])
print(c_3d)
print(c_3d.shape)

[[1 2 3 4 5]
 [4 5 6 8 9]
 [7 8 5 7 9]
 [1 1 1 5 6]
 [2 2 2 4 5]]
(5, 5)


In [47]:
#dtype
#gives the type of data which type of data it is storing whether int , float , etc
c_3d = np.array([[1,2,3,4,5],[4,5,6,8,9],[7,8,5,7,9],[1,1,1,5,6],[2,2,2,4,5]])
print(c_3d)
print(c_3d.dtype)

[[1 2 3 4 5]
 [4 5 6 8 9]
 [7 8 5 7 9]
 [1 1 1 5 6]
 [2 2 2 4 5]]
int32


In [50]:
c_array = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(c_array)
c_array_2 = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(c_array_2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


# ones and zeros

In [62]:
#creating  matrix by ones and zeros function
a= np.ones([4,4] , dtype = int)
print(a)
b = np.zeros([3,3],dtype = int)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [65]:
a= np.ones([4,4] , dtype = str)
print(a)
b = np.zeros([3,3],dtype = str) # blank matrix will occur
print(b)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
[['' '' '']
 ['' '' '']
 ['' '' '']]


In [67]:
a= np.ones([4,4] , dtype = bool)
print(a)
b = np.zeros([3,3],dtype = bool)
print(b)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False]
 [False False False]
 [False False False]]


# empty function

In [72]:
em_mx = np.empty((4,4)) # gives garbage value
print(em_mx)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# arrange function

In [75]:
#syntax :- np.arange(start_value , end_value , step)
ar_1d = np.arange(13)
print(ar_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [78]:
ar_1d = np.arange(1 , 100)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [85]:
ar_1d = np.arange(1 , 100 , 1)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


# linspace function

In [97]:
#syntax :- np.linspace(start_value , end_value , np of value b/w start and end)
np.linspace(1,2,50)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [100]:
np.linspace(1,100,10) #difference is same b/w values

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [102]:
s = np.linspace(1,10,25)
print(s)

[ 1.     1.375  1.75   2.125  2.5    2.875  3.25   3.625  4.     4.375
  4.75   5.125  5.5    5.875  6.25   6.625  7.     7.375  7.75   8.125
  8.5    8.875  9.25   9.625 10.   ]


# resahpe function

In [107]:
print("one dimension array by linspace")
s = np.linspace(1,10,25)
print(s)
d = s.reshape(5,5)
print(d)


one dimension array by linspace
[ 1.     1.375  1.75   2.125  2.5    2.875  3.25   3.625  4.     4.375
  4.75   5.125  5.5    5.875  6.25   6.625  7.     7.375  7.75   8.125
  8.5    8.875  9.25   9.625 10.   ]
[[ 1.     1.375  1.75   2.125  2.5  ]
 [ 2.875  3.25   3.625  4.     4.375]
 [ 4.75   5.125  5.5    5.875  6.25 ]
 [ 6.625  7.     7.375  7.75   8.125]
 [ 8.5    8.875  9.25   9.625 10.   ]]


In [119]:
print("by linspace function:")

arr = np.linspace(1,12,12 , dtype = int)
arr2 = arr.reshape(3,2,2)
print(arr2)
print(arr)
print("by arange function:")
array_1 = np.arange(1,13,1)
print(array_1)
array_2 = array_1.reshape(3,2,2)
print(array_2)

by linspace function: [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
by arange function:[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# ravel function

In [120]:
#convert multi dimensional to one dimensional
c_3d = np.array([[[1,2,3],[4,5,6],[7,8,5]],[[1,1,1],[2,2,2],[3,3,3]]])
c_3d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 1, 1, 1, 2, 2, 2, 3, 3, 3])

# transpose function

In [125]:
#transpose() or T() row to column or column to row
c_3d = np.array([[1,2,3,4,5],[4,5,6,8,9],[7,8,5,7,9],[1,1,1,5,6],[2,2,2,4,5]])
# c_3d.transpose()
c_3d.T

array([[1, 4, 7, 1, 2],
       [2, 5, 8, 1, 2],
       [3, 6, 5, 1, 2],
       [4, 8, 7, 5, 4],
       [5, 9, 9, 6, 5]])

In [133]:
array1 = np.arange(1,10).reshape(3,3)
array2 = np.arange(1,10).reshape(3,3)
print(array1)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# mathematical operation using Numpy

In [134]:
print(array1+array2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [135]:
print(array1-array2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [136]:
print(array1*array2) #this is not actual matrix multiplication(elemenmt to element)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [139]:
print(array1@array2)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [141]:
print(array1.dot(array2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [142]:
np.add(array1,array2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [145]:
np.divide(array1,array2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [147]:
np.subtract(array1,array2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Maximum and Minimum

In [3]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(arr1.argmax())
print(arr1.max())


8
9


In [6]:
arr1.max(axis=0)

array([7, 8, 9])

In [7]:
arr1.max(axis=1)

array([3, 6, 9])

In [9]:
arr1.min(axis=1)

array([1, 4, 7])

In [10]:
arr1.min(axis=0)

array([1, 2, 3])

In [11]:
np.sum(arr1)

45

In [12]:
np.sum(arr1,axis=0) #column wise

array([12, 15, 18])

In [13]:
np.sum(arr1,axis=1) #row wise

array([ 6, 15, 24])

In [14]:
np.mean(arr1) #mean of the array

5.0

In [16]:
np.median(arr1) #median of the array

5.0

In [17]:
np.sqrt(arr1) #square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [18]:
#standard deviation
np.std(arr1)

2.581988897471611

In [19]:
np.exp(arr1) #exponent values

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [21]:
np.log(arr1) #log base e of every element

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [65]:
np.log10(arr1) # log base 10 of every element 

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.95424251, 1.        , 1.04139269, 1.07918125],
       [1.23044892, 1.25527251, 1.2787536 , 1.30103   ],
       [1.39794001, 1.41497335, 1.43136376, 1.44715803],
       [1.51851394, 1.53147892, 1.54406804, 1.5563025 ]])

# Slicing

In [26]:
array = np.arange(1,101).reshape(10,10)
print(array)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
2


In [30]:
array[0,0] #array[row,column]

1

In [29]:
array[4,5]

46

In [31]:
array[:] #all rows all column

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [35]:
array[:,2:5] #slicing of array

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25],
       [33, 34, 35],
       [43, 44, 45],
       [53, 54, 55],
       [63, 64, 65],
       [73, 74, 75],
       [83, 84, 85],
       [93, 94, 95]])

In [37]:
array[2:5,2:6]

array([[23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46]])

In [39]:
array[:,6:8]

array([[ 7,  8],
       [17, 18],
       [27, 28],
       [37, 38],
       [47, 48],
       [57, 58],
       [67, 68],
       [77, 78],
       [87, 88],
       [97, 98]])

In [42]:
array[1:3,]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [45]:
array[6:8,]

array([[61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [46]:
print(array)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [48]:
array[2:4,2:4]

array([[23, 24],
       [33, 34]])

In [51]:
array[5:8,4:7]

array([[55, 56, 57],
       [65, 66, 67],
       [75, 76, 77]])

In [52]:
array2 = np.arange(1,41).reshape(5,8)
print(array2)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]]


In [64]:
arr1 = array2[:,0:4]
print(arr1)
print("\n")
arr2 = array2[:,4:8]
print(arr2)
print("\n")
print(np.add(arr1,arr2))
# print(arr1+arr2)

[[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]
 [25 26 27 28]
 [33 34 35 36]]


[[ 5  6  7  8]
 [13 14 15 16]
 [21 22 23 24]
 [29 30 31 32]
 [37 38 39 40]]


[[ 6  8 10 12]
 [22 24 26 28]
 [38 40 42 44]
 [54 56 58 60]
 [70 72 74 76]]


In [68]:
arr1.max()

36

In [69]:
arr2.max()

40

In [70]:
np.sum(arr1,axis = 0)

array([ 85,  90,  95, 100])

In [71]:
np.sum(arr2,axis=0)

array([105, 110, 115, 120])

In [72]:
np.sum(arr1,axis = 1)

array([ 10,  42,  74, 106, 138])

In [73]:
np.sum(arr2,axis = 1)

array([ 26,  58,  90, 122, 154])

# Random()

In [81]:
import random
np.random.random(20)

array([0.25602605, 0.04804745, 0.33773901, 0.30840001, 0.15226558,
       0.07854504, 0.36166333, 0.94278882, 0.02820411, 0.94390458,
       0.71468708, 0.44891594, 0.21708281, 0.8506968 , 0.84050398,
       0.77025273, 0.51589955, 0.43733056, 0.41031781, 0.54057292])

In [83]:
np.random.random((3,3))

array([[0.09986492, 0.48403801, 0.31767561],
       [0.38962519, 0.24720741, 0.29133943],
       [0.49075131, 0.63221939, 0.05552892]])

# Randit()

In [127]:
np.random.randint(1000) # generating random value between 0 to 100

934

In [134]:
np.random.randint(20,25)

23

In [135]:
np.random.randint(20,25,(3,3))

array([[20, 24, 24],
       [22, 22, 23],
       [22, 20, 23]])

In [136]:
np.random.randint(20,25,3)

array([22, 24, 22])

In [137]:
np.random.randint(20,25,(4,4)) #one matrix of 4X4

array([[21, 21, 20, 23],
       [22, 21, 24, 22],
       [24, 20, 23, 23],
       [22, 22, 20, 24]])

In [138]:
np.random.randint(20,25,(2,5,5)) #two matrix of 5X5

array([[[23, 22, 23, 21, 23],
        [22, 23, 20, 21, 24],
        [22, 24, 23, 24, 23],
        [21, 24, 24, 22, 23],
        [24, 21, 23, 22, 24]],

       [[20, 24, 24, 20, 21],
        [24, 20, 23, 23, 20],
        [20, 20, 23, 20, 24],
        [24, 22, 20, 24, 20],
        [20, 24, 24, 24, 22]]])

# Choice()

In [165]:
p = [1,2,3,4,5,6,7,8,9]
np.random.choice(p) #select from specific given list 

5

In [168]:
p = [1,2,3,4,5,6,7,8,9]
np.random.choice(p,5) 

array([4, 5, 6, 7, 4])

# Permutation

In [185]:
k = [1,2,3]
np.random.permutation(k)

array([2, 3, 1])

In [190]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [191]:
#joining by column
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [193]:
np.concatenate((arr1,arr2),axis = 1) #joining row wise

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

# Split()

In [195]:
np.split(array,2) #spliting array in two parts

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]]),
 array([[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [8]:
area = np.random.randint(600,2500,100)
bhk = np.random.randint(2,4,100)
price = np.random.randint(400000,5000000,100)
balcony = np.random.randint(1,6,100)
data = np.zeros((100,4),dtype=int)
data[:,0] = area
data[:,1] = bhk
data[:,2] = price
data[:,3] = balcony
print(data)

[[   2014       2 4338574       1]
 [   2202       2 3281929       3]
 [   1196       3 3898828       3]
 [   1687       2 3691393       4]
 [    691       3 1718358       4]
 [   1650       3 3630785       4]
 [   1764       2 2887085       5]
 [    669       3  693827       2]
 [   1989       3 1963206       5]
 [   1613       3 1066713       2]
 [   1201       3 4882230       4]
 [   1326       2 4541597       4]
 [    768       3 4669100       3]
 [   2161       3 4836820       3]
 [   2130       2 1009884       2]
 [   1714       3 2980594       3]
 [    792       2 1135332       3]
 [   2441       3  919522       5]
 [   2441       3  715621       3]
 [   2049       3 2588785       4]
 [   2078       2 2773366       1]
 [    940       3  433928       5]
 [   1639       3 2658422       3]
 [   1813       3 2255295       5]
 [   1433       2 2244634       5]
 [   2272       3 4119982       1]
 [   1463       3 2449753       3]
 [    824       3  653773       3]
 [   1910       3 18